collection_name : smart_travel_guides
persist_path : data/chroma_db

md5_store : md5.txt

allowed_extensions : ['.pdf', '.txt']
# 文本切分配置
chunk_size: 600
chunk_overlap: 60
separators : ['\n\n', '\n', ' ', '.', '?', '!', '。', '？', '！']
# 检索配置
top_k: 3
#score_threshold: 0.4

storage_path : data/chat_history